### ISSUE TITLE
Enable generated tests

### ISSUE THREAD

**Issue by ctreatma** [equinix-labs/metal-go#51]
The OpenAPI generator produces client code and test stubs.  The generated tests are skipped by default; they don't include any mocking (so they can't run as unit tests) and they don't do any of the setup that would be needed to run as integration tests (for example, creating dependent resources).

To make the generated tests valuable, we need to make them run.  We should identify a small number of tests and figure out how to enable them (either as unit tests or as integration tests) and come up with a strategy for keeping them enabled moving forward (possibly by creating post-patch files to modify the test code when it is regenerated).

**Comment by t0mk** [comment]
@ctreatma I will drop my 2 cents here, as I have been working on packngo for years, and because I have been thinking about adding integration tests to metal-python. IMO the shortest way towards limited success here is to write a couple of integration tests by hand, covering the most used parts of the API, and then add where necessary.

I just checked the generated tests and they seem useless. 

I am always against unit tests in golang clients, because the code is statically type-checked on the compilation, and the only verification-worth state is returned from the API (and tested during integration tests hopefully). 

Replaying recorded HTTP traffic only makes sense if you'd like to save money for API usage (not our case I would say). It also needs to be redone when the API changes.

Limited set of integration tests would show that, even though we regenerated the code at some point, the basic functionality was kept intact.

**Comment by ctreatma** [comment]
I don't particularly have a preference for whether the existing tests are copied over as a starting point or not.  In terms of the test files, the most important change is to stop generating them.

Replaying recorded HTTP traffic is a tradeoff:  it makes it easier for folks who do not have their expenses comped to run the tests, and it allows the tests to run faster.  The benefit of a tool like `go-vcr` is that the tests can still be run against the live API instead of the recordings, which enables us to run scheduled workflows against the live API, and to update the recordings if needed based on the outcome of those scheduled tests.

**Comment by ctreatma** [comment]
This repo will be deprecated shortly, and I don't think we'll implement testing as described in this issue in [equinix/equinix-sdk-go](https://github.com/equinix/equinix-sdk-go).
